sugarcube-2:
  macros:
    clearDivineTransformations:
      name: clearDivineTransformations
    lanLink:
      name: lanLink
      container: true
    lanSwitch:
      name: lanSwitch
    icon:
      name: icon
    clearAnimalTransformations:
      name: clearAnimalTransformations
    updatesidebarimg:
      name: updatesidebarimg
    transformationAlteration:
      name: transformationAlteration
    numberStepper:
      name: numberStepper
    lanListbox:
      name: lanListbox
      container: true
    radiobuttonsfrom:
      name: radiobuttonsfrom
      container: true
    numberslider:
      name: numberslider
